Secret: Make wl-copy optional

diff --git a/src/kubectl-secret b/src/kubectl-secret
--- a/src/kubectl-secret
+++ b/src/kubectl-secret
@@ -117,6 +117,11 @@ function secret-show {
 }
 
 function secret-copy {
+    if ! command -v wl-copy 2>/dev/null; then
+        error "Missing command 'wl-copy'. Install it for 'copy' to work!"
+        return 1
+    fi
+
     k8s-logged-in
 
     secret-show "${@}" | wl-copy -n
